services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recicla-ai-backend-prod
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_KEY: ${API_KEY}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - .:/app
    networks:
      - recicla-ai-network

networks:
  recicla-ai-network:
    driver: bridge
